os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y ack-grep cpanminus libgmp-dev mercurial python3 python3-setuptools perl libperl-dev valgrind
    - sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
      # For cmake-3.x - probably not needed in trusty.
      # - sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - sudo apt-get update -q
    - sudo apt-get install -y cmake cmake-data ninja-build python3-pip
install:
    - ( cd fc-solve/source && hg clone -u make-code-suitable-for-fc-solve https://bitbucket.org/shlomif/patsolve-shlomif )
      # - sudo easy_install3 pip
    - sudo -H python3 -m pip install random2
    - sudo -H `which python3` -m pip install random2
    - which python3
      # - /usr/bin/env python3 -m sys -m random2 -c 'print(sys.executable)'
    - sudo cpanm base Carp Cwd Data::Dumper Digest::SHA Env::Path File::Path File::Spec Games::Solitaire::Verify Games::Solitaire::Verify::Solution Inline Inline::C IPC::Open2 lib List::MoreUtils parent Path::Tiny Storable strict String::ShellQuote Template Test::Data::Split Test::Data::Split::Backend::Hash Test::Differences Test::More Text::Sprintf::Named Test::Trap warnings YAML::XS
    - wget http://web-cpan.shlomifish.org/downloads/libtap-1.12.0.tar.bz2
    - tar -xvf libtap-1.12.0.tar.bz2
    - ( mkdir B && cd B && cmake ../libtap-1.12.0 && make && sudo make install )
    - ( a="$(pwd)"; mkdir B2 && cd B2 && hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules && cd shlomif-cmake-modules/shlomif-cmake-modules && cp -f "$(pwd)"/Shlomif_Common.cmake "$a"/fc-solve/source/cmake/ )

perl:
    - "5.22"
python:
    - "3.5"
script: "export FC_SOLVE__MULT_CONFIG_TESTS__TRACE=1 ; cd fc-solve/source && perl scripts/multi_config_tests.pl"
