addons:
    apt:
        update: true
        packages:
            - asciidoc
            # Avoid downgrading cmake from 3.12.x to 3.10.x
            # - cmake
            # - cmake-data
            - cpanminus
            - dbtoepub
            - docbook-xsl
            - docbook-xsl-ns
            - graphicsmagick
            - gperf
            - libapr1-dev
            - libc6-dbg
            - libcmocka-dev
            - libdb5.3-dev
            - libgd-dev
            - libgmp-dev
            - libgoogle-perftools-dev
            - libhunspell-dev
            - libperl-dev
            - libxml2-dev
            - lynx
            - mercurial
            - ninja-build
            - perl
            - python3
            - python3-pip
            - python3-setuptools
            - silversearcher-ag
            - strip-nondeterminism
            - valgrind
            - xsltproc
os: linux
# dist: trusty
# dist: xenial
dist: bionic
go:
    - '1.11.x'
language: c
python:
    - '3.6'
before_install:
    - if test "$WHAT" = "normal"; then . fc-solve/scripts/ci-before-install.bash ; fi
install:
    - if test "$WHAT" = "normal"; then . fc-solve/scripts/ci-install-stage.bash ; elif test "$WHAT" = "buildproc"; then . fc-solve/scripts/ci-docker-test--install.bash ; fi
perl:
    - "5.24"
script:
    - if test "$WHAT" = "normal"; then export XML_CATALOG_FILES="/etc/xml/catalog $HOME/markup-validator/htdocs/sgml-lib/catalog.xml" ; bash fc-solve/scripts/run-ci-tests.bash ; elif test "$WHAT" = "buildproc" ; then cd fc-solve/source/ && perl ../scripts/docker-test.pl ; fi
cache:
    ccache: true
    directories:
        - $HOME/fc-solve-tests-reruns-cache
        - $HOME/perl_modules
        - fc-solve/source/avl-2.0.3
matrix:
    allow_failures:
        - env: WHAT=buildproc
    include:
        - os: linux
          env:
              - WHAT=normal
        - os: linux
          env:
              - WHAT=buildproc
services:
    - docker
