os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake cmake-data cpanminus gperf libgmp-dev libgoogle-perftools-dev libperl-dev mercurial ninja-build python3 python3-setuptools perl python3-pip silversearcher-ag valgrind
install:
    - ( cd fc-solve/source && git clone --branch make-code-suitable-for-fc-solve https://github.com/shlomif/patsolve.git patsolve-shlomif )
    - sudo -H `which python3` -m pip install cffi
    - sudo -H `which python3` -m pip install random2
    - sudo -H `which python3` -m pip install Zenfilter
      # Temporary workaround for a problem in running the Inline::C test
      # suite with latest EU::MM - install Inline::C with no tests.
      #     - https://github.com/ingydotnet/inline-c-pm/issues/49 .
    - sudo cpanm --notest Inline::C
    - sudo cpanm Task::FreecellSolver::Testing
    - sudo cpanm Test::Code::TidyAll
    - wget http://web-cpan.shlomifish.org/downloads/libtap-1.12.0.tar.bz2
    - tar -xvf libtap-1.12.0.tar.bz2
    - ( mkdir B && cd B && cmake ../libtap-1.12.0 && make && sudo make install )
    - ( a="$(pwd)"; mkdir B2 && cd B2 && hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules && cd shlomif-cmake-modules/shlomif-cmake-modules && cp -f "$(pwd)"/Shlomif_Common.cmake "$a"/fc-solve/source/cmake/ )
perl:
    - "5.24"
python:
    - "3.5"
script:
    - export FC_SOLVE__MULT_CONFIG_TESTS__TRACE=1 ; set -o pipefail ; cd fc-solve/source ; perl ../scripts/multi_config_tests.pl 2>&1 | zenfilter --count-step=500 --last=500 --filter='^Running:.*?\[idx\s*=\s*[0-9]+\s*/\s*[0-9]+'
