os: linux
dist: trusty
language: c
python:
    - '3.6'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y asciidoc cmake cmake-data cpanminus docbook-xsl docbook-xsl-ns gperf libdb5.3-dev libgd-dev libgmp-dev libgoogle-perftools-dev libhunspell-dev libperl-dev mercurial ninja-build python3 python3-setuptools perl python3-pip silversearcher-ag valgrind wml xsltproc
      # - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      # - sudo cpanm Text::Hunspell
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    # For wml
    - cpanm --notest Bit::Vector Class::XSAccessor GD Getopt::Long IO::All Image::Size Term::ReadKey
    - cpanm --quiet --notest Alien::Tidyp Pod::Xhtml Task::Latemp
    - bash fc-solve/scripts/install-git-cmakey-program-system-wide.bash 'git' 'src' 'https://github.com/thewml/website-meta-language.git'
    - bash fc-solve/scripts/install-git-cmakey-program-system-wide.bash 'git' 'installer' 'https://github.com/thewml/latemp.git'
    - ( cd .. && git clone https://github.com/thewml/wml-extended-apis.git && cd wml-extended-apis/xhtml/1.x && bash Install.bash )
    - ( cd .. && git clone https://github.com/shlomif/wml-affiliations.git && cd wml-affiliations/wml && bash Install.bash )
    - ( cd .. && git clone https://github.com/thewml/latemp.git && cd latemp/support-headers && perl install.pl )
install:
    - sudo -H `which python3` -m pip install cffi cookiecutter pycotap random2 six Zenfilter
      # For G-S-V dzil
    - cpanm --quiet --notest Dist::Zilla Pod::Coverage::TrustPod Pod::Weaver::Section::Support Test::EOL Test::NoTabs Test::Kwalitee Test::Pod Test::Pod::Coverage
      # For the website
    - cpanm --quiet --notest App::XML::DocBook::Builder Carp::Always Code::TidyAll::Plugin::ESLint Code::TidyAll::Plugin::TSLint Data::Munge File::Find::Object::Rule File::ReadBackwards File::Update File::Which HTML::Latemp::GenMakeHelpers HTML::Spelling::Site HTML::TokeParser::Simple IO::All List::MoreUtils Moo MooX MooX::late Parallel::ForkManager Path::Tiny Perl::Critic Perl::Tidy Template Test::Code::TidyAll Test::File::Find::CaseCollide Test::HTML::Recursive::DeprecatedTags Test::HTML::Tidy::Recursive Test::HTML::Tidy::Recursive::Strict Text::WrapAsUtf8 XML::Feed
    - cpanm --quiet --notest Task::FreecellSolver::Testing
    - (cd cpan/Games-Solitaire-Verify/Games-Solitaire-Verify/ && dzil authordeps --missing | cpanm --notest)
    - (cd .. && wget http://web-cpan.shlomifish.org/downloads/libtap-1.12.0.tar.bz2 && tar -xvf libtap-1.12.0.tar.bz2 && ( mkdir B && cd B && cmake ../libtap-1.12.0 && make && sudo make install ) ; )
    - ( cd fc-solve/site/wml && bash -x bin/install-npm-deps.sh )
    # For the site
    - gem install sass compass compass-blueprint
perl:
    - "5.24"
python:
    - "3.5"
script:
    - prove root-tests/t/*.t
    - export FC_SOLVE__MULT_CONFIG_TESTS__TRACE=1 SKIP_SPELL_CHECK=1 ; set -o pipefail ; cd fc-solve/source ; perl ../scripts/multi_config_tests.pl 2>&1 | zenfilter --count-step=500 --last=500 --filter='^Running:\s*\{' --suppress-last-on="All tests successful\\.\\n*\\Z"
sudo: required
cache:
    ccache: true
    directories:
    - $HOME/perl_modules
# services:
#     - docker
