---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - choco install wget
    - wget -O strawberry-perl-5.24.0.1-64bit.msi http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-64bit.msi
    # - ps: (new-object net.webclient).DownloadFile('http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-64bit.msi', 'strawberry-perl-5.24.0.1-64bit.msi')
    - dir *.msi
    # - ps: msiexec /i strawberry-perl-5.24.0.1-64bit.msi /quiet /qn /norestart /log install.log INSTALLDIR="C:\strawberry"
    - msiexec /i strawberry-perl-5.24.0.1-64bit.msi /quiet /qn /norestart /log install.log INSTALLDIR="C:\strawberry"
    # - type install.log
    - dir C:\
    - dir C:\strawberry
    # - dir C:\msys64
    # - dir C:\msys64\mingw64
    # - dir C:\msys64\mingw64\bin
    - dir c:\Python35-x64
    - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
    - SET PATH=C:\Python35-x64;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - python3 -mpip install random2
    - perl -v
    - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\make.exe
    # - SET PATH=C:\msys64\mingw64\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/_P5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/_P5
    - SET PERL_MB_OPT=--install_base C:/_P5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/_P5
    - perl -v
    - cpanm --notest Devel::Trace File::Which IPC::Run Path::Tiny Task::FreecellSolver::Testing Test::PerlTidy
    - hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules fc-solve/source/cmake/sfc
    - copy fc-solve\source\cmake\sfc\shlomif-cmake-modules\Shlomif_Common.cmake fc-solve\source\cmake\
    - git clone -b make-code-suitable-for-fc-solve git://github.com/shlomif/patsolve.git fc-solve/source/patsolve-shlomif
    - if not exist C:\libtap mkdir C:\libtap
    - if not exist C:\libtap\gperf-3.0.4.tar.gz wget -O C:\libtap\gperf-3.0.4.tar.gz http://ftp.gnu.org/pub/gnu/gperf/gperf-3.0.4.tar.gz
    - copy C:\libtap\gperf-3.0.4.tar.gz .
    - tar -xvf gperf-3.0.4.tar.gz
    # - if not exist C:\libtap\bin\gperf.exe cd gperf-3.0.4 && sh configure --prefix=C:/libtap && gmake && gmake install && cd ..
    # - if not exist C:\libtap\bin\gperf.exe cd gperf-3.0.4 && perl -e "$ENV{PATH} = qq#C:\\msys64\\mingw64\\bin;$ENV{PATH}#; system('sh configure --prefix=C:/libtap && gmake && gmake install');" && cd ..
    - cd gperf-3.0.4 && perl -e "if (-e qq#C:\\libtap\\bin\\gperf.exe#) { exit(0); } $ENV{PATH} = qq#C:\\msys64\\mingw64\\bin;$ENV{PATH}#; system('sh configure --prefix=C:/libtap') or system('gmake') or system('gmake install');" && cd ..
    - git clone -b cmake https://github.com/shlomif/libtap
    - mkdir libtap\b
    - cd libtap\b
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    # - cmake -G "MSYS Makefiles" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM% -DCMAKE_INSTALL_PREFIX=C:\libtap ..
    - cmake -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM% -DCMAKE_INSTALL_PREFIX=C:\libtap ..
    - echo %PATH%
    - gmake
    - gmake install
    - dir C:\libtap\include
    - cd ..\..\
build: off
test_script:
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - set LIBRARY_PATH=C:\libtap\lib
    - set CMAKE_LIBRARY_PATH=C:\libtap\lib
    - set LD_LIBRARY_PATH=C:\libtap\lib
    - set CPATH=C:\libtap\include
    - set PATH=C:\libtap\bin;%PATH%
    - set HARNESS_BREAK=1
    - set HARNESS_VERBOSE=1
    - set FCS_USE_TEST_RUN=1
    - mkdir fc-solve\b
    - cd fc-solve\b
    # - perl ../source/Tatzer -G "MSYS Makefiles"
    - perl ../source/Tatzer -G "MinGW Makefiles"
    - SET PATH=C:\projects\fc-solve\fc-solve\scripts\win32;%PATH%
    - echo %PATH%
    # - gperf
    - gmake
    - gmake boards
    - dir *gen_ms*
    # Trying this hack to take more precendence for Inline::C / etc.
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\_P5\bin;%PATH%
    # - perl ../source/run-tests.pl --glob='{[a-c],delta,[e-i]}*.{py,t}'
    - perl ../source/run-tests.pl --glob='{[f-g],[i-z]}*.{py,t}'
    # - perl ../source/run-tests.pl --glob='{a,b,board-gen,c,cmpdigest,d,verify--}*.{py,t}'
    # - perl ../source/run-tests.pl --glob='d*.{py,t}'
    # - perl ../source/run-tests.pl --glob='delta-states-perl*.{py,t}'
    # - perl ../source/run-tests.pl --execute="gdb --command=..\..\scripts\appveyor.gdb c:\Python35-x64\python3.exe"
    # - perl ../source/run-tests.pl --execute="perl ..\..\source\t\t\depth-based-multi-queue.t"
    # - perl ../source/run-tests.pl --execute="c:\msys64\mingw64\bin\gdb --command=..\..\scripts\appveyor.gdb c:\strawberry\perl\bin\perl.exe"
cache:
    - C:\libtap
    - C:\_P5

shallow_clone: true

