---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    # - dir C:\msys64
    # - dir C:\msys64\mingw64
    # - dir C:\msys64\mingw64\bin
    - choco install strawberryperl -version 5.20.1.1
    - choco install wget
    - dir c:\Python35-x64
    - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
    - SET PATH=C:\Python35-x64;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - python3 -mpip install random2
    - perl -v
    - if not exist C:\Perl5 mkdir C:\Perl5
    - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\make.exe
    - SET PATH=C:\msys64\mingw64\bin;C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/Perl5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
    - SET PERL_MB_OPT=--install_base C:/Perl5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
    - cpanm --notest Path::Tiny Task::FreecellSolver::Testing
    - hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules fc-solve/source/cmake/sfc
    - copy fc-solve\source\cmake\sfc\shlomif-cmake-modules\Shlomif_Common.cmake fc-solve\source\cmake\
    - git clone -b make-code-suitable-for-fc-solve git://github.com/shlomif/patsolve.git fc-solve/source/patsolve-shlomif
    - if not exist C:\libtap mkdir C:\libtap
    - if not exist C:\libtap\gperf-3.0.4.tar.gz wget -O C:\libtap\gperf-3.0.4.tar.gz http://ftp.gnu.org/pub/gnu/gperf/gperf-3.0.4.tar.gz
    - copy C:\libtap\gperf-3.0.4.tar.gz .
    - tar -xvf gperf-3.0.4.tar.gz
    - if not exist C:\libtap\bin\gperf.exe cd gperf-3.0.4 && sh configure --prefix=C:/libtap && gmake && gmake install && cd ..
    - git clone -b cmake https://github.com/shlomif/libtap
    - mkdir libtap\b
    - cd libtap\b
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - cmake -G "MSYS Makefiles" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM% -DCMAKE_INSTALL_PREFIX=C:\libtap ..
    - gmake
    - gmake install
    - dir C:\libtap\include
    - cd ..\..\
build: off
test_script:
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - set LIBRARY_PATH=C:\libtap\lib
    - set CMAKE_LIBRARY_PATH=C:\libtap\lib
    - set LD_LIBRARY_PATH=C:\libtap\lib
    - set CPATH=C:\libtap\include
    - set PATH=C:\libtap\bin;%PATH%
    - set HARNESS_BREAK=1
    - set HARNESS_VERBOSE=1
    - set FCS_USE_TEST_RUN=1
    - mkdir fc-solve\b
    - cd fc-solve\b
    - perl ../source/Tatzer -G "MSYS Makefiles"
    - gmake
    - gmake boards
    - dir *gen_ms*
    # Trying this hack to take more precendence for Inline::C / etc.
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    # - perl ../source/run-tests.pl --glob='{a,b,board-gen,cmpdigest,verify--}*.{py,t}'
    - set PYTHONPATH=C:\projects\fc-solve\fc-solve\source\t\lib
    - cd ..\source\t
    - gdb --command=..\..\scripts\appveyor.gdb c:\Python35-x64\python3.exe
cache:
    - C:\libtap
    - C:\Perl5

shallow_clone: true

